version: 5.0.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - LLVM_5_0
  
image: Visual Studio 2017

skip_commits:
  files:
    - '**\*.md'

nuget:
  disable_publish_on_pr: true
  account_feed: false
  project_feed: true

build_script:
  - ps: .\BuildAll.ps1

test_script:
  - ps: .\Invoke-UnitTests.ps1

artifacts:
  - path: .\BuildOutput\Nuget\LLvm.NET.*.nupkg
  - path: .\BuildOutput\Nuget\LibLLVM.NET.*.nupkg
