version: 5.0.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

image: Visual Studio 2017

environment:
  docspush_email: 32618965+cibuild-telliam@users.noreply.github.com
  docspush_username: cibuild-telliam
  docspush_access_token:
    secure: QqWCIyFM6uBBbkW1jnlVGsMQWy+9aPY9rhD56oNT2L/0Cmw2bynROEsrUrOPpBrk

skip_commits:
  files:
    - 'docs\**'

init:
  - git config --global core.safecrlf false
  - git config --global core.autocrlf input

nuget:
  disable_publish_on_pr: true
  account_feed: false
  project_feed: true

build_script:
  - ps: .\BuildAll.ps1

after_build:
  - ps: .\Build-Docs.ps1

test_script:
  - ps: .\Invoke-UnitTests.ps1

artifacts:
  - path: .\BuildOutput\Nuget\LLvm.NET.*.nupkg
  - path: .\BuildOutput\Nuget\LibLLVM.NET.*.nupkg

on_success:
  - ps: .\Push-Docs.ps1
